<template>
  <div class="loadingio-spinner-pulse-5t84e7qjhwv">
    <div class="ldio-r43p2otpij">
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
</template>

<style scoped>
@keyframes ldio-r43p2otpij-1 {
  0% {
    top: 36px;
    height: 128px;
  }
  50% {
    top: 60px;
    height: 80px;
  }
  100% {
    top: 60px;
    height: 80px;
  }
}
@keyframes ldio-r43p2otpij-2 {
  0% {
    top: 41.99999999999999px;
    height: 116.00000000000001px;
  }
  50% {
    top: 60px;
    height: 80px;
  }
  100% {
    top: 60px;
    height: 80px;
  }
}
@keyframes ldio-r43p2otpij-3 {
  0% {
    top: 48px;
    height: 104px;
  }
  50% {
    top: 60px;
    height: 80px;
  }
  100% {
    top: 60px;
    height: 80px;
  }
}
.ldio-r43p2otpij div {
  position: absolute;
  width: 30px;
}
.ldio-r43p2otpij div:nth-child(1) {
  left: 35px;
  background: #71dae1;
  animation: ldio-r43p2otpij-1 1.3333333333333333s cubic-bezier(0, 0.5, 0.5, 1)
    infinite;
  animation-delay: -0.26666666666666666s;
}
.ldio-r43p2otpij div:nth-child(2) {
  left: 85px;
  background: #008af4;
  animation: ldio-r43p2otpij-2 1.3333333333333333s cubic-bezier(0, 0.5, 0.5, 1)
    infinite;
  animation-delay: -0.13333333333333333s;
}
.ldio-r43p2otpij div:nth-child(3) {
  left: 135px;
  background: #2f34c6;
  animation: ldio-r43p2otpij-3 1.3333333333333333s cubic-bezier(0, 0.5, 0.5, 1)
    infinite;
  animation-delay: undefineds;
}

.loadingio-spinner-pulse-5t84e7qjhwv {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
}
.ldio-r43p2otpij {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-r43p2otpij div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
