<template>
  <div class="loadingio-spinner-ellipsis-y7e5h6cqxfr">
    <div class="ldio-0ofx3rw4s4i">
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
</template>

<style scoped>
@keyframes ldio-0ofx3rw4s4i {
  0% {
    transform: translate(14px, 82px) scale(0);
  }
  25% {
    transform: translate(14px, 82px) scale(0);
  }
  50% {
    transform: translate(14px, 82px) scale(1);
  }
  75% {
    transform: translate(82px, 82px) scale(1);
  }
  100% {
    transform: translate(150px, 82px) scale(1);
  }
}
@keyframes ldio-0ofx3rw4s4i-r {
  0% {
    transform: translate(150px, 82px) scale(1);
  }
  100% {
    transform: translate(150px, 82px) scale(0);
  }
}
@keyframes ldio-0ofx3rw4s4i-c {
  0% {
    background: #91bcc6;
  }
  25% {
    background: #194645;
  }
  50% {
    background: #0a69aa;
  }
  75% {
    background: #07abcc;
  }
  100% {
    background: #91bcc6;
  }
}
.ldio-0ofx3rw4s4i div {
  position: absolute;
  width: 36px;
  height: 36px;
  border-radius: 50%;
  transform: translate(82px, 82px) scale(1);
  background: #91bcc6;
  animation: ldio-0ofx3rw4s4i 2s infinite cubic-bezier(0, 0.5, 0.5, 1);
}
.ldio-0ofx3rw4s4i div:nth-child(1) {
  background: #07abcc;
  transform: translate(150px, 82px) scale(1);
  animation:
    ldio-0ofx3rw4s4i-r 0.5s infinite cubic-bezier(0, 0.5, 0.5, 1),
    ldio-0ofx3rw4s4i-c 2s infinite step-start;
}
.ldio-0ofx3rw4s4i div:nth-child(2) {
  animation-delay: -0.5s;
  background: #91bcc6;
}
.ldio-0ofx3rw4s4i div:nth-child(3) {
  animation-delay: -1s;
  background: #07abcc;
}
.ldio-0ofx3rw4s4i div:nth-child(4) {
  animation-delay: -1.5s;
  background: #0a69aa;
}
.ldio-0ofx3rw4s4i div:nth-child(5) {
  animation-delay: -2s;
  background: #194645;
}
.loadingio-spinner-ellipsis-y7e5h6cqxfr {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
}
.ldio-0ofx3rw4s4i {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-0ofx3rw4s4i div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
