<template>
  <div class="loadingio-spinner-double-ring-8s7hd0kbzhj">
    <div class="ldio-07puk4kmug9y">
      <div></div>
      <div></div>
      <div><div></div></div>
      <div><div></div></div>
    </div>
  </div>
</template>

<style scoped>
@keyframes ldio-07puk4kmug9y {
  0% {
    transform: rotate(0);
  }
  100% {
    transform: rotate(360deg);
  }
}
.ldio-07puk4kmug9y div {
  box-sizing: border-box !important;
}
.ldio-07puk4kmug9y > div {
  position: absolute;
  width: 144px;
  height: 144px;
  top: 28px;
  left: 28px;
  border-radius: 50%;
  border: 16px solid #000;
  border-color: #63c6ff transparent #63c6ff transparent;
  animation: ldio-07puk4kmug9y 2s linear infinite;
}

.ldio-07puk4kmug9y > div:nth-child(2),
.ldio-07puk4kmug9y > div:nth-child(4) {
  width: 108px;
  height: 108px;
  top: 46px;
  left: 46px;
  animation: ldio-07puk4kmug9y 2s linear infinite reverse;
}
.ldio-07puk4kmug9y > div:nth-child(2) {
  border-color: transparent #0088ff transparent #0088ff;
}
.ldio-07puk4kmug9y > div:nth-child(3) {
  border-color: transparent;
}
.ldio-07puk4kmug9y > div:nth-child(3) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-07puk4kmug9y > div:nth-child(3) div:before,
.ldio-07puk4kmug9y > div:nth-child(3) div:after {
  content: '';
  display: block;
  position: absolute;
  width: 16px;
  height: 16px;
  top: -16px;
  left: 48px;
  background: #63c6ff;
  border-radius: 50%;
  box-shadow: 0 128px 0 0 #63c6ff;
}
.ldio-07puk4kmug9y > div:nth-child(3) div:after {
  left: -16px;
  top: 48px;
  box-shadow: 128px 0 0 0 #63c6ff;
}

.ldio-07puk4kmug9y > div:nth-child(4) {
  border-color: transparent;
}
.ldio-07puk4kmug9y > div:nth-child(4) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-07puk4kmug9y > div:nth-child(4) div:before,
.ldio-07puk4kmug9y > div:nth-child(4) div:after {
  content: '';
  display: block;
  position: absolute;
  width: 16px;
  height: 16px;
  top: -16px;
  left: 30px;
  background: #0088ff;
  border-radius: 50%;
  box-shadow: 0 92px 0 0 #0088ff;
}
.ldio-07puk4kmug9y > div:nth-child(4) div:after {
  left: -16px;
  top: 30px;
  box-shadow: 92px 0 0 0 #0088ff;
}
.loadingio-spinner-double-ring-8s7hd0kbzhj {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
}
.ldio-07puk4kmug9y {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-07puk4kmug9y div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
