<script setup lang="ts">
import type { GeneratedResponse } from '@/types/inbox.type';
import type { SchemaFormRef } from '@/types/schemaform.type';

const props = withDefaults(defineProps<{
  formRef?: SchemaFormRef;
  disabled?: boolean;
  label: string;
  tooltip?: string;
  editorFieldName: string;
}>(), {
  disabled: false,
  label: 'Re-write'
});

const emits = defineEmits<{
  (e: 'rewrite', value: string): void;
  (e: 'cancel'): void;
  (e: 'modalClose'): void;
}>();

const attrs = useAttrs();
const { replaceNewlines } = useUtilityFns();
const { featureSubscribed } = usePermissions();
const { defaultBreakpoints } = useCommonBreakPoints();

const selectedSuggestion = ref<string>('');
const reWriteDialog = ref(false);
const suggestDialog = ref(false);
const isAutoreply = ref(false);
const isSummarizing = ref(false);
const gettingSuggested = ref<GeneratedResponse[]>([]);
const currentEditorText = ref<string>();
const currentIndex = ref<number>(0);
const aiFeature = ref();
const subscribeDialog = ref(false);

const currentData = computed(() => {
  if (gettingSuggested.value) {
    return gettingSuggested.value[currentIndex.value];
  }
});

const currentChannelType = computed(() => {
  switch (props.formRef?.schemaFormValues?.channel || props.formRef?.schemaFormValues?.type) {
    case 'EMAIL':
      return 'email-reply';
    case 'SUPPORT':
      return 'comment';
    default:
      return undefined;
  }
});

function handleSuccess(data: GeneratedResponse[]) {
  reWriteDialog.value = false;
  suggestDialog.value = true;
  gettingSuggested.value.push(...data);
}

async function handleCloseSuggest() {
  isSummarizing.value = false;
  gettingSuggested.value = [];
}

function showNextSuggest() {
  currentIndex.value
    = (currentIndex.value + 1) % gettingSuggested.value?.length;
}

function handleSelectSuggestion(data: any) {
  selectedSuggestion.value = replaceNewlines(data as string);
  currentEditorText.value = replaceNewlines(data as string);
  props.formRef?.setFieldValue(props.editorFieldName, replaceNewlines(data as string));
  emits('rewrite', replaceNewlines(data as string));
  suggestDialog.value = false;
}

function handleOpenDialog(autoreply = false) {
  isAutoreply.value = autoreply;
  reWriteDialog.value = true;
}
function handleRewrite() {
  if (featureSubscribed('ai_features', 'content_rewrite') === false) {
    aiFeature.value = 'Rewrite';
    subscribeDialog.value = true;
    return false;
  }
  handleOpenDialog();
}
</script>

<template>
  <span v-tooltip="tooltip" class="inline-block">
    <Button
      :label="label"
      size="small"
      class="max-w-max"
      v-bind="attrs"
      :disabled="disabled"
      @click="handleRewrite"
    />
  </span>

  <Dialog
    v-model:visible="suggestDialog"
    :modal="true"
    append-to="body"
    :header="`This ${
      isSummarizing ? 'summary' : 'message'
    } is generated by BrightAssistant`"
    :breakpoints="defaultBreakpoints"
    :style="{ width: '35vw' }"
    content-class="border-round-bottom-md"
    @hide="handleCloseSuggest"
  >
    <div class="pb-2">
      <span v-html="replaceNewlines(currentData?.html as string)" />
      <div class="flex justify-content-end mt-3">
        <Button
          label="Cancel"
          class="p-button-sm p-button-danger"
          @click="suggestDialog = false"
        />
        <!-- <Button
          v-if="isSummarizing"
          label="Copy"
          class="p-button-sm ml-2"
          @click="copyToClipboard(currentData?.html as string, 'Summary')"
        /> -->
        <Button
          v-if="!isSummarizing"
          label="Continue"
          class="p-button-sm ml-2"
          @click="handleSelectSuggestion(currentData?.html)"
        />
        <Button
          v-if="gettingSuggested.length > 1"
          label="Next"
          class="p-button-sm ml-2"
          @click="showNextSuggest"
        />
      </div>
    </div>
  </Dialog>
  <Dialog
    v-model:visible="reWriteDialog"
    :modal="true"
    append-to="body"
    :header="`Which tone you want to use for your ${
      isAutoreply ? 'auto-' : ''
    }reply?`"
    :breakpoints="defaultBreakpoints"
    :style="{ width: '45vw' }"
    content-class="border-round-bottom-md"
  >
    <MailsGenerateSuggestion
      :type="currentChannelType"
      :message="(formRef?.schemaFormValues?.body as string)"
      :is-autoreply="isAutoreply"
      @modal-close="reWriteDialog = false"
      @success="handleSuccess"
    />
  </Dialog>
</template>

<style lang="scss" scoped>

</style>
